### ISSUE TITLE
Jest output shows errors with watching

### ISSUE THREAD

**Issue by SgtPooki** [orta/vscode-jest#101]
```
2017-05-02 21:26 node[77005] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)

2017-05-02 21:26 node[77005] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)

events.js:154

      throw er; // Unhandled 'error' event
      ^

Error: watch null EMFILE
    at exports._errnoException (util.js:856:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)


```

**Comment by SgtPooki** [comment]
Disregard. Installing watchman fixed this.
