### ISSUE TITLE
Extension not finding my jest-config.json

### ISSUE THREAD

**Issue by tamj0rd2** [orta/vscode-jest#122]
I have the following line in settings.json:
```json
  "jest.pathToConfig": "${workspaceRoot}/.vscode/jest-config.json"
```

For some reason this extension still isn't finding my config file. Running the command `node ./node_modules/jest/bin/jest.js --config ./.vscode/jest-config.js` works without any issues. However because the extension isn't finding my jest-config.json tests are failing saying that `fetch` is undefined.

I have this message in the developer console:

```
ENOENT: no such file or directory, open 'extension-output-#4': Error: ENOENT: no such file or directory, open 'extension-output-#4'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at fs.readFileSync (fs.js:468:33)
    at fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at parse (/home/tam/.vscode/extensions/Orta.vscode-jest-2.2.0/node_modules/jest-editor-support/build/parsers/BabylonParser.js:21:16)
    at JestExt.triggerUpdateDecorations (/home/tam/.vscode/extensions/Orta.vscode-jest-2.2.0/out/src/JestExt.js:132:29)
    at vscode.window.onDidChangeActiveTextEditor.editor (/home/tam/.vscode/extensions/Orta.vscode-jest-2.2.0/out/src/fileChangeWatchers.js:9:21)
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:14715)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:53565)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:390025
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:14715)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:53565)
    at t.$acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:346353)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:312304)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:176531)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:177208)
```

**Comment by tamj0rd2** [comment]
I've managed to get this working by looking through other issues. Since I'm using create-react-app all I needed to do was add this to my settings.json:
```json
"jest.pathToJest": "npm run test --"
```
