### ISSUE TITLE
Jest stuck - keeps spinning, no output

### ISSUE THREAD

**Issue by jchapuis** [orta/vscode-jest#128]
### Environment

1. `node -v`: v6.10.3
2. `npm -v`: 3.10.10
4. `npm ls react-scripts` (if you haven’t ejected): 
`-- (empty)
npm ERR! code 1

1. Operating system: Windows

### Steps to Reproduce
No matter if start my project, or stop/start Jest - it keeps spinning and does nothing. One of five it suddenly works, then gets stuck again after a while.

There are some warnings in the developer console:

![image](https://user-images.githubusercontent.com/7502497/28216336-946a5094-68b1-11e7-8e54-d3550e75a2ae.png)

**Comment by GregOnNet** [comment]
Hey,

I experience the same error.
Having a look in the Output of Jest there is an error while spawning the git process.

![image](https://user-images.githubusercontent.com/444278/28258579-39673bd0-6ad2-11e7-9f62-1d6f90866b77.png)

```
Error: spawn git ENOENT
    at exports._errnoException (util.js:1014:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

## System

- Windows 10 
- npm 5.0.3
- node v8.1.0
- VSCode 1.14.1

I would love to see the Jest integration working in my VSCode. :-)
If you need further information please contact me.

Thanks in advance
Greg

**Comment by GregOnNet** [comment]
**UPDATE**
For me it seems that the problem is that VSCode does not resolve the path to the installed git binary.
I don't think that my problems relate to `vscode-jest` itself.

**Comment by bookman25** [comment]
Have you tried running jest standalone without the plugin?  This plugin doesn't talk directly to git in any way, all of that logic is handled directly by jest.

**Comment by marcionicolau** [comment]
I get this from Developer Tools 
MacOS X
VSCode: 1.16.0
Jest: 21.0.2

```js
shell.ts:419 [Orta.vscode-jest] Cannot read property 'testRegex' of undefined: TypeError: Cannot read property 'testRegex' of undefined
at JestExt.wouldJestRunURI (/Users/nicolau/.vscode/extensions/Orta.vscode-jest-2.3.0/out/src/JestExt.js:253:64)
	at JestExt.canUpdateDecorators (/Users/nicolau/.vscode/extensions/Orta.vscode-jest-2.3.0/out/src/JestExt.js:249:34)
	at JestExt.triggerUpdateDecorations (/Users/nicolau/.vscode/extensions/Orta.vscode-jest-2.3.0/out/src/JestExt.js:131:19)
	at vscode.window.onDidChangeActiveTextEditor.editor (/Users/nicolau/.vscode/extensions/Orta.vscode-jest-2.3.0/out/src/fileChangeWatchers.js:9:21)
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:393153
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at e.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:351598)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:423958)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280554)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280244)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:279271
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:281190
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:56058
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:102495)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by bookman25** [comment]
This error points to a failure to load jest settings.  Any chance you have a sample repo we can clone to try to reproduce?

**Comment by dennisreimann** [comment]
I experience a similar problem, here is the output of the Developer Tools Console:

```
shell.ts:459 [Orta.vscode-jest] Cannot read property 'forEach' of null: TypeError: Cannot read property 'forEach' of null
	at JestExt.sortDecorationBlocks (/Users/dennisreimann/.vscode/extensions/Orta.vscode-jest-2.4.5/out/src/JestExt.js:187:19)
	at JestExt.updateDotDecorators (/Users/dennisreimann/.vscode/extensions/Orta.vscode-jest-2.4.5/out/src/JestExt.js:220:74)
	at JestExt.triggerUpdateDecorations (/Users/dennisreimann/.vscode/extensions/Orta.vscode-jest-2.4.5/out/src/JestExt.js:171:14)
	at vscode.window.onDidChangeActiveTextEditor.editor (/Users/dennisreimann/.vscode/extensions/Orta.vscode-jest-2.4.5/out/src/fileChangeWatchers.js:9:21)
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84411)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86133)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:479691
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84411)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86133)
	at e.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:430508)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:509443)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354476)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353503
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355422
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:85128
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84411)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86133)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:144114)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
```

This happens on startup, after that the Jest extension ist stuck with "testing changes".

Jest extension version: `2.4.5`
Jest and Jest CLI version: `21.2.1`

jest.config.js: 

```
module.exports = {
  'mapCoverage': true,
  'moduleFileExtensions': [
    'js',
    'vue'
  ],
  'moduleNameMapper': {
    '^@/(.*)$': '<rootDir>/src/vue/$1'
  },
  'snapshotSerializers': [
    '<rootDir>/node_modules/jest-serializer-vue'
  ],
  testMatch: [
    '**/test/unit/**/?(*.)spec.js'
  ],
  'transform': {
    '^.+\\.js$': '<rootDir>/node_modules/babel-jest',
    '.*\\.(vue)$': '<rootDir>/node_modules/vue-jest'
  }
}
```

**Comment by seanpoulter** [comment]
Thanks for sharing your problem @dennisreimann. Looking through [`sortDecorationBlocks`](https://github.com/orta/vscode-jest/blame/master/src/JestExt.ts#L239) and `updateDotDecorators` it looks like `assertions` was likely `null`. This was recently fixed by @BBB in #169 but it hasn't been published yet.

**Comment by seanpoulter** [comment]
@dennisreimann, the fix has been published.
Closing since we seem to have resolved these.

**Comment by dennisreimann** [comment]
I can confirm that the error message in the VS Code dev console is gone now. Nevertheless the extension is still stuck with "testing changes". There is no more error output I can send to debug, the Jest console is empty as well.

<img width="782" alt="jest" src="https://user-images.githubusercontent.com/886/33358938-fcf45138-d4cb-11e7-8a3e-987d9a6229d9.png">

Any way I can provide more feedback/debugging info? Thanks!

**Comment by BenAychh** [comment]
Probably related to https://github.com/facebook/jest/issues/4419, try creating a git repo inside or waiting until the fix is released. At least this fixed it for me.

**Comment by seanpoulter** [comment]
I missed your reply, sorry @dennisreimann.

Is the project set up in a git or hg repo?
Can you reproduce it with a small repo we can clone?
Are you willing to try debugging the extension with our help?

**Comment by dennisreimann** [comment]
@seanpoulter unfortunately this isn't a public project.

> Are you willing to try debugging the extension with our help?

Of course – is this something we can have a quick look at together in a screensharing session? Otherwise I will try to come up with a similar setup in a separate repo you can reproduce the problem with.

**Comment by seanpoulter** [comment]
I'd be happy to try and figure this out on a screenshare @dennisreimann!

Here's where I'd suggest we start to figure out what's happened so far, and where it's stuck:
- clone this repo  `git clone https://github.com/orta/vscode-jest.git`
- open the repo folder in Visual Studio Code
- find the `testsHaveStartedRunning()` method in `JestExt.ts`:
  - comment out the call to `clear()` the Jest output channel
  - add a breakpoint in the method -- if we're stuck here, then we can try and figure out how we get here
- start the "Launch Extension" debug task
- in the window that opens, open your repo that causes problems

**Comment by dennisreimann** [comment]
Ok, I checked whether or not I can come up with more debuggable output using the steps you provided. I guess this is related, the debugging console outputs this message a few seconds after I save a test file:

```
Array[1]
  0:Object
    code:"ECONNREFUSED"
    errno:"ECONNREFUSED"
    syscall:"connect"
    address:"0.0.0.0"
    port:443
```

However, I don't get to the breakpoint I've set in the `testsHaveStartedRunning` method. So lets just conect via screensharing. Please send me an email (see the mail address in my GH profile) and we can arrange a time this weekend or in the upcoming week :)

**Comment by dennisreimann** [comment]
I found the culprit: We are using [Webpack's resolve.alias feature](https://webpack.js.org/configuration/resolve/#resolve-alias). This leads to files that cannot be resolved by the vscode-jest extension, so the tests can't be run.

The relevant webpack config part:

```js
module.exports = {
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      '@': resolve('src'),
    }
  }
}
```

An import example:

```js
// with resolve.alias 
import FormField from '@/vue/components/FormField'
// regular import
import FormField from '../../components/FormField'
```

If this is something you would like to fix, you can leave the issue open and I'll try to provide a test project. Otherwise you can close this issue as this case might be to special to address. 

Thanks for your help!

**Comment by seanpoulter** [comment]
Wow, glad you found it @dennisreimann!

I'm happy to keep the issue open and make sure we're properly handling the `moduleNameMapper` option in your `jest.config.js`. There's something going on if it works from the command line but not in the extension. That should be pretty quick to test.

**Comment by seanpoulter** [comment]
I'm not convinced that the module resolution is the root cause. This [minimal repo](https://github.com/seanpoulter/vscode-jest--128) worked OK. :confused: The only time it I got the "testing changes" spinner was before setting up a `git` repo and getting the `Error: This promise must be present when running with -o.` error from #142.
