### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by capaj** [orta/vscode-jest#68]
I looked into the console this time when trying to enable vscode-jest and saw that this error is popping up:
```
extensionHost.ts:293[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'split' of undefinedA.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] TypeError: Cannot read property 'split' of undefined
    at TestReconciler.lineOfError (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:123:32)
    at assertions.map.assertion (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:96:21)
    at Array.map (native)
    at TestReconciler.mapAssertions (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:85:23)
    at results.testResults.forEach.file (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:50:26)
    at Array.forEach (native)
    at TestReconciler.updateFileWithJestStatus (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:45:25)
    at JestExt.updateWithData (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:254:25)
    at Runner.jestProcess.on.on (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:41:18)
    at emitOne (events.js:96:13)
    at Runner.emit (events.js:188:7)
    at readFile (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/Runner.js:61:18)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)A.logExtensionHostMessage @ extensionHost.ts:293
shell.ts:541Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
    at TestReconciler.lineOfError (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:123:32)
    at assertions.map.assertion (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:96:21)
    at Array.map (native)
    at TestReconciler.mapAssertions (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:85:23)
    at results.testResults.forEach.file (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:50:26)
    at Array.forEach (native)
    at TestReconciler.updateFileWithJestStatus (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:45:25)
    at JestExt.updateWithData (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:254:25)
    at Runner.jestProcess.on.on (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:41:18)
    at emitOne (events.js:96:13)
    at Runner.emit (events.js:188:7)
    at readFile (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/Runner.js:61:18)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

```

I have version 2.0.5 on vscode 1.8.1

**Comment by ferewuz** [comment]
Getting similar error on version 2.0.5 and vscode 1.10.2 : 
```[Extension Host] TypeError: Cannot read property 'split' of undefined
    at TestReconciler.lineOfError (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:123:32)
    at assertions.map.assertion (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:96:21)
    at Array.map (native)
    at TestReconciler.mapAssertions (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:85:23)
    at results.testResults.forEach.file (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:50:26)
    at Array.forEach (native)
    at TestReconciler.updateFileWithJestStatus (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:45:25)
    at JestExt.updateWithData (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:254:25)
    at Runner.jestProcess.on.on (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:41:18)
    at emitOne (events.js:96:13)
    at Runner.emit (events.js:188:7)
    at readFile (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/Runner.js:61:18)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)d.logExtensionHostMessage @ extensionHost.ts:282
shell.ts:426Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
    at TestReconciler.lineOfError (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:123:32)
    at assertions.map.assertion (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:96:21)
    at Array.map (native)
    at TestReconciler.mapAssertions (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:85:23)
    at results.testResults.forEach.file (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:50:26)
    at Array.forEach (native)
    at TestReconciler.updateFileWithJestStatus (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/TestReconciler.js:45:25)
    at JestExt.updateWithData (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:254:25)
    at Runner.jestProcess.on.on (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:41:18)
    at emitOne (events.js:96:13)
    at Runner.emit (events.js:188:7)
    at readFile (/Users/vanclevstik/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/Runner.js:61:18)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)e.onUnexpectedError @ shell.ts:426
```

**Comment by bookman25** [comment]
Does this still reproduce in the current version of `vscode-jest`?  The `jest-editor-support` package (which is what is throwing the error) has had some significant changes that may have addressed this.  If the issue still occurs with the latest version the line numbers might have some relevance and I can reopen/look into.
