### ISSUE TITLE
Cannot read property concat of undefined in jest-editor-support

### ISSUE THREAD

**Issue by guyca** [orta/vscode-jest#71]
I've just installed this amazing plugin - thanks a lot for all the hard work put into it.

Unfortunately, even though the plugin seems to load and run tests fine (I see the little `jest` button at the status bar in the bottom of the screen) - I don't see the pass/fail indicators in the gutter (those precious green/red dots)

In the dev console, is see the following log each time I navigate to one of my `.spec.js` files:

```
TypeError: Cannot read property 'concat' of undefined
    at babylonParser (/Users/guy/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/parsers/BabylonParser.js:57:32)
    at Object.parse (/Users/guy/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/ScriptParser.js:31:12)
    at JestExt.triggerUpdateDecorations (/Users/guy/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:118:51)
    at JestExt.updateWithData (/Users/guy/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:262:14)
    at Runner.jestProcess.on.on (/Users/guy/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:41:18)
    at emitOne (events.js:96:13)
    at Runner.emit (events.js:188:7)
    at readFile (/Users/guy/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/Runner.js:61:18)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

I'm working on a react-native project and to be honest, I'm pretty new to the whole Js ecosystem - it's possible my setup is wrong and or missing some config?

Orta.vscode-jest-2.0.5
react-native 0.38.2
vs code 1.8.1

**Comment by bookman25** [comment]
It looks like it's trying to parse your .babelrc file and not finding a plugins section in the file.  Just based on the stacktrace message.

**Comment by guyca** [comment]
hmm, I added an empty plugins object to my .bablerc file - still getting same stack trace 😢 

```js
{
  "presets": ["react-native"],
  "plugins": []
}
```
