### ISSUE TITLE
Causes tests to fail when using stackgl/headless-gl

### ISSUE THREAD

**Issue by jingchan** [orta/vscode-jest#74]
When using `stackgl/headless-gl`, running jest from command line works fine, but this plugin will fail:

```
import GL from 'gl';
let gl = GL(100, 100);  // <-- Errors
```

Causes this error:
```
    TypeError: bindFramebuffer(GLenum, WebGLFramebuffer)
      
      at WebGLRenderingContext.bindFramebuffer (node_modules/gl/webgl.js:1054:11)
      at WebGLRenderingContext.bindFramebuffer (node_modules/gl/webgl.js:1068:22)
      at resizeDrawingBuffer (node_modules/gl/webgl.js:4092:20)
      at Object.allocateDrawingBuffer (node_modules/gl/webgl.js:4079:3)
      at createContext (node_modules/gl/node_index.js:105:9)
      at Object.<anonymous> (shader.spec.js:10:53)
```

**Comment by jingchan** [comment]
Closing because, after some digging, I'm more inclined to believe this is an issue with the other library.
