### ISSUE TITLE
jest runs but editor integration fails

### ISSUE THREAD

**Issue by tzapu** [orta/vscode-jest#80]
Hello,

Tried to use the extension today, but it seems to work only in part for me.
- got jest auto running in the bar
- the output shows the problems
- no update snapshot dialog is shown
- no editor integration showing problems is shown
- i get these errors in the developer tools console
```
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:133 [Extension Host] Uncaught Exception:  SyntaxError: Unexpected token, expected , (31:6)d.logExtensionHostMessage @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:133
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:133 [Extension Host] SyntaxError: Unexpected token, expected , (31:6)
    at Parser.pp$5.raise (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp.expect (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:1615:33)
    at Parser.pp$7.flowParseTypeParameterDeclaration (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:4645:12)
    at Parser.parseMaybeAssign (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:5674:33)
    at Parser.pp$3.parseExprListItem (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:4101:16)
    at Parser.parseExprListItem (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:5425:24)
    at Parser.pp$3.parseCallExpressionArguments (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3410:20)
    at Parser.pp$3.parseSubscripts (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3370:31)
    at Parser.pp$3.parseExprSubscripts (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3341:15)
    at Parser.pp$3.parseMaybeUnary (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:5694:20)
    at Parser.pp$1.parseVar (/Users/alex/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:2205:24)
```
- vscode version is 2.1.6

Not sure what else i could provide as details, please let me know.
Cheers

**Comment by TuiKiken** [comment]
The same problem.

**Comment by Rauttis** [comment]
Similar issue here, works fine in one of my projects but not in another, not sure what the difference is.

```
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:138 Unexpected token, expected , (58:39): SyntaxError: Unexpected token, expected , (58:39)
    at Parser.pp$5.raise (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp.expect (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:1615:33)
    at Parser.pp$7.flowParseTypeParameterDeclaration (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:4645:12)
    at Parser.parseMaybeAssign (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:5674:33)
    at Parser.pp$3.parseExprListItem (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:4101:16)
    at Parser.parseExprListItem (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:5425:24)
    at Parser.pp$3.parseCallExpressionArguments (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3410:20)
    at Parser.pp$3.parseSubscripts (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3370:31)
    at Parser.pp$3.parseExprSubscripts (/Users/niklasa/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/node_modules/babylon/lib/index.js:3341:15)
```

**Comment by eranimo** [comment]
Same here. Very strange, because this feature worked when I initially downloaded the extension but broke when I did a refresh when I installed eslint.

**Comment by etiennedi** [comment]
I'm having the same issue and I just cloned the repo and started to investigate a bit. The error occurs in `JestExt.triggerUpdateDecorations` when calling ` this.parseResults = parse(editor.document.uri.fsPath);`.

`parse` is imported from `jest-editor-support`. So, there is most likely nothing wrong in `vscode-jest`. It'll probably an issue with either `jest-editor-support` or even `babylon` directly.

@orta How do we go form here? I'd love to contribute. I'll check jest-editor-support for some issues next. Regardless of this particular error, how do you feel about wrapping critical function calls like this in a try...catch? We could still throw to the console (or even use a VSCode error dialog). But more importantly, we could add a lot of info where the error occurred. Something like "Couldn't update Decorations, parsing the source file failed with the following error..." would have probably helped here quite a bit.

**Comment by etiennedi** [comment]
Update: I believe I found the issue, see https://github.com/facebook/jest/issues/3070 at jest.

**Comment by orta** [comment]
Sorry, I'm out on my honeymoon - so can't dig into anything for a few weeks
I'm afraid

**Comment by tzapu** [comment]
happy honeymoon dude :D

**Comment by etiennedi** [comment]
My PR on facebook/jest has been merged and the issue there has been closed. Let's keep this one open until the changes in jest and therefore jest-editor-support have been released. At least the error I had is gone with the changes.

**Comment by bookman25** [comment]
vscode-jest should have the latest version of jest-editor-support at this time.
