### ISSUE TITLE
no such file or directory, open 'extension-output-#1': Error: ENOENT: no such file or directory, open 'extension-output-#1'

### ISSUE THREAD

**Issue by stijnvanderlaan** [orta/vscode-jest#81]
throws Error and stops working when switching to "output" or "debug console" tab.

**Comment by aranw** [comment]
I seem to be getting the same issue 

```
shell.ts:475ENOENT: no such file or directory, open 'extension-output-#2': Error: ENOENT: no such file or directory, open 'extension-output-#2'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:178:20)
    at fs.readFileSync (fs.js:508:33)
    at fs.readFileSync (ELECTRON_ASAR.js:511:29)
    at babylonParser (/Users/aranw/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/parsers/BabylonParser.js:50:16)
    at Object.parse (/Users/aranw/.vscode/extensions/Orta.vscode-jest-2.0.5/node_modules/jest-editor-support/build/ScriptParser.js:31:12)
    at JestExt.triggerUpdateDecorations (/Users/aranw/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/JestExt.js:118:51)
    at vscode.window.onDidChangeActiveTextEditor.editor (/Users/aranw/.vscode/extensions/Orta.vscode-jest-2.0.5/out/src/extension.js:39:27)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:16423)e.onUnexpectedError @ shell.ts:475(anonymous function) @ shell.ts:435e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by roblingle** [comment]
Same here, years later. I assume this is a VSCode or local environment config issue, anyone have ideas?
